version: '3.8'
services:
  linkshortner:
    image: node:12-alpine
    container_name: linkshortner
    build: .
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: mysql_server
      ELASTIC_URL: http://host.docker.internal:9200
      NODE_ENV: development
      HOST: http://localhost/
      DOMAIN: localhost
      PORT: 3000
      API_KEY: djjdsbois901jjsd49833993838
      SHOW_DB_NAME_QUERIES: 'true'
    command: npm run start
    links:
      - mysql_server
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:8.0
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: 1234567aws
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: my_user
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - '3307:3306'
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
volumes:
    mysql:
    mysql_config: